# Generated by Django 5.2.16 on 2026-07-24 02:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modules.core.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('business_name', models.CharField(default='Gestión Financiera', max_length=120, verbose_name='nombre del negocio')),
                ('logo', models.FileField(blank=True, upload_to='logos/', verbose_name='logo')),
                ('daily_late_fee', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='recargo diario')),
                ('collection_days', models.JSONField(default=modules.core.models.default_collection_days, verbose_name='días de cobranza')),
                ('payment_methods', models.JSONField(default=modules.core.models.default_payment_methods, verbose_name='métodos de pago')),
                ('available_frequencies', models.JSONField(default=modules.core.models.default_frequencies, verbose_name='frecuencias disponibles')),
                ('max_installments', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)], verbose_name='máximo de cuotas')),
                ('charge_sundays', models.BooleanField(default=True, verbose_name='generar recargo los domingos')),
                ('late_fee_after_partial_payment', models.BooleanField(default=True, verbose_name='continuar recargo después de un pago parcial')),
                ('allow_advance_payments', models.BooleanField(default=False, verbose_name='permitir pagos adelantados')),
                ('whatsapp_message', models.TextField(default='Hola {nombre}. Te recordamos que tenés una cuota pendiente de {monto} con vencimiento {vencimiento}.', verbose_name='mensaje de WhatsApp')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuración',
                'constraints': [models.CheckConstraint(condition=models.Q(('daily_late_fee__gte', Decimal('0.00'))), name='settings_late_fee_non_negative'), models.CheckConstraint(condition=models.Q(('max_installments__gte', 1)), name='settings_max_installments_positive')],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('first_name', models.CharField(max_length=80, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='apellido')),
                ('dni', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='teléfono')),
                ('address', models.CharField(max_length=180, verbose_name='dirección')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='barrio')),
                ('address_reference', models.CharField(blank=True, max_length=200, verbose_name='referencia del domicilio')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['last_name', 'first_name', 'pk'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='customer_name_idx'), models.Index(fields=['is_active'], name='customer_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dni__isnull', False)), fields=('dni',), name='customer_unique_non_null_dni')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='product_unique_name')],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('product_description', models.CharField(max_length=250, verbose_name='descripción congelada')),
                ('delivery_date', models.DateField(verbose_name='fecha de entrega')),
                ('cash_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='precio contado')),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto financiado')),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal')], max_length=16, verbose_name='frecuencia')),
                ('installment_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cantidad de cuotas')),
                ('daily_late_fee', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='recargo diario congelado')),
                ('first_due_date', models.DateField(verbose_name='primer vencimiento')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], default='active', max_length=16, verbose_name='estado')),
                ('cancelled_on', models.DateField(blank=True, null=True, verbose_name='fecha de cancelación')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='motivo de cancelación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.customer', verbose_name='cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-delivery_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='clave de operación')),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe')),
                ('payment_method', models.CharField(max_length=40, verbose_name='método de pago')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('status', models.CharField(choices=[('registered', 'Registrado'), ('voided', 'Anulado')], default='registered', max_length=16, verbose_name='estado')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='anulado el')),
                ('void_reason', models.TextField(blank=True, verbose_name='motivo de anulación')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.customer', verbose_name='cliente')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-payment_date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('due_date', models.DateField(verbose_name='vencimiento')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe original')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='core.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'ordering': ['due_date', 'number', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CollectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('attempt_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('result', models.CharField(choices=[('did_not_pay', 'No pagó'), ('absent', 'Ausente'), ('promised', 'Prometió pagar'), ('other', 'Otro')], max_length=20, verbose_name='resultado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_attempts', to='core.customer', verbose_name='cliente')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_attempts', to='core.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'intento de cobranza',
                'verbose_name_plural': 'intentos de cobranza',
                'ordering': ['-attempt_date', '-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LateFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('fee_date', models.DateField(verbose_name='fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fees', to='core.installment', verbose_name='cuota')),
            ],
            options={
                'verbose_name': 'recargo',
                'verbose_name_plural': 'recargos',
                'ordering': ['fee_date', 'pk'],
                'indexes': [models.Index(fields=['fee_date'], name='late_fee_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('installment', 'fee_date'), name='late_fee_unique_installment_date'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='late_fee_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('component', models.CharField(choices=[('late_fee', 'Recargo'), ('principal', 'Capital')], max_length=16, verbose_name='componente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe aplicado')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='core.installment', verbose_name='cuota')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.payment', verbose_name='pago')),
            ],
            options={
                'verbose_name': 'aplicación de pago',
                'verbose_name_plural': 'aplicaciones de pago',
                'ordering': ['payment_id', 'installment__due_date', 'component', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('payment', 'installment', 'component'), name='allocation_unique_payment_installment_component'), models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='allocation_amount_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='sale_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', 'status'], name='sale_customer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('cash_price__gt', Decimal('0.00'))), name='sale_cash_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('financed_amount__gt', Decimal('0.00'))), name='sale_financed_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1)), name='sale_installment_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('daily_late_fee__gte', Decimal('0.00'))), name='sale_late_fee_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'status'], name='payment_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date'], name='payment_customer_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0.00'))), name='payment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='installment_due_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['sale', 'due_date'], name='installment_sale_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('sale', 'number'), name='installment_unique_sale_number'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='installment_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', Decimal('0.00'))), name='installment_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='collectionattempt',
            index=models.Index(fields=['attempt_date'], name='attempt_date_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionattempt',
            index=models.Index(fields=['customer', 'attempt_date'], name='attempt_customer_date_idx'),
        ),
    ]
