# Generated by Django 5.2.16 on 2026-07-29 18:31

from django.db import migrations, models


def enable_monthly_frequency(apps, schema_editor):
    business_settings = apps.get_model("core", "BusinessSettings")
    for settings in business_settings.objects.all():
        frequencies = list(settings.available_frequencies or [])
        if "monthly" not in frequencies:
            frequencies.append("monthly")
            settings.available_frequencies = frequencies
            settings.save(update_fields=["available_frequencies"])


def disable_monthly_frequency(apps, schema_editor):
    business_settings = apps.get_model("core", "BusinessSettings")
    for settings in business_settings.objects.all():
        frequencies = [
            frequency
            for frequency in (settings.available_frequencies or [])
            if frequency != "monthly"
        ]
        settings.available_frequencies = frequencies
        settings.save(update_fields=["available_frequencies"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_collectionattempt_attempt_unique_sale_date_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Semanal"),
                    ("biweekly", "Quincenal"),
                    ("monthly", "Mensual"),
                ],
                max_length=16,
                verbose_name="frecuencia",
            ),
        ),
        migrations.RunPython(enable_monthly_frequency, disable_monthly_frequency),
    ]
