# Generated by Django 5.2.16 on 2026-07-29 23:35

import django.core.validators
import modules.core.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_sale_down_payment_and_payment_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssettings",
            name="payment_methods",
            field=models.JSONField(
                default=modules.core.models.default_payment_methods, verbose_name="medios de pago"
            ),
        ),
        migrations.AlterField(
            model_name="collectionattempt",
            name="result",
            field=models.CharField(
                choices=[
                    ("did_not_pay", "No pagó"),
                    ("absent", "No estaba en el domicilio"),
                    ("promised", "Prometió pagar"),
                    ("other", "Otro resultado"),
                ],
                max_length=20,
                verbose_name="resultado",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="kind",
            field=models.CharField(
                choices=[("installment", "Pago de cuota"), ("initial", "Pago inicial")],
                default="installment",
                max_length=16,
                verbose_name="tipo de movimiento",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=40, verbose_name="medio de pago"),
        ),
        migrations.AlterField(
            model_name="sale",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="pago inicial",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Semanal"),
                    ("biweekly", "Cada 2 semanas"),
                    ("monthly", "Mensual"),
                ],
                max_length=16,
                verbose_name="frecuencia",
            ),
        ),
    ]
