# Generated by Django 5.2.16 on 2026-08-06 21:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clarify_argentina_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='loan_disbursement_method',
            field=models.CharField(blank=True, max_length=40, verbose_name='medio de entrega del préstamo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='interés total del préstamo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='operation_type',
            field=models.CharField(choices=[('product', 'Venta de producto'), ('loan', 'Préstamo de dinero')], default='product', max_length=16, verbose_name='tipo de operación'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.product', verbose_name='producto'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('loan_interest_rate__gte', Decimal('0.00'))), name='sale_loan_interest_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'product'), ('product__isnull', False)), models.Q(('operation_type', 'loan'), ('product__isnull', True)), _connector='OR'), name='sale_product_matches_operation_type'),
        ),
    ]
