# Generated by Django 5.2.16 on 2026-08-27 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sale_loan_disbursement_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=120, verbose_name='acción')),
                ('path', models.CharField(max_length=500, verbose_name='ruta')),
                ('method', models.CharField(max_length=10, verbose_name='método')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='estado HTTP')),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección remota')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadatos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento de auditoría',
                'verbose_name_plural': 'eventos de auditoría',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_created_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx')],
            },
        ),
    ]
