# Generated by Django 5.2.16 on 2026-08-24 01:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_sale_loan_disbursement_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "revision_number",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="número de edición",
                    ),
                ),
                ("reason", models.TextField(verbose_name="motivo de la edición")),
                ("snapshot", models.JSONField(verbose_name="copia completa anterior")),
                (
                    "archived_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="archivada el"),
                ),
            ],
            options={
                "verbose_name": "versión anterior de venta",
                "verbose_name_plural": "versiones anteriores de ventas",
                "ordering": ["-archived_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="enviado al archivo seguro"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="deletion_reason",
            field=models.TextField(blank=True, verbose_name="motivo del borrado"),
        ),
        migrations.AddField(
            model_name="sale",
            name="edit_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="cantidad de ediciones",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["deleted_at"], name="customer_deleted_idx"),
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.CheckConstraint(
                condition=models.Q(("edit_count__gte", 0), ("edit_count__lte", 2)),
                name="sale_edit_count_between_zero_and_two",
            ),
        ),
        migrations.AddField(
            model_name="salerevision",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="core.sale",
                verbose_name="venta actual",
            ),
        ),
        migrations.AddIndex(
            model_name="salerevision",
            index=models.Index(fields=["archived_at"], name="sale_revision_archived_idx"),
        ),
        migrations.AddConstraint(
            model_name="salerevision",
            constraint=models.UniqueConstraint(
                fields=("sale", "revision_number"), name="sale_revision_unique_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="salerevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_number__gte", 1), ("revision_number__lte", 2)),
                name="sale_revision_number_between_one_and_two",
            ),
        ),
    ]
