# Generated by Django 5.2.16 on 2026-08-24 02:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_safe_archive_and_sale_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='allow_exceptional_sale_edits',
            field=models.BooleanField(default=False, help_text='Permite corregir una venta con pagos o visitas. Se desactiva automáticamente después de usarla una vez.', verbose_name='habilitar una corrección excepcional de venta'),
        ),
        migrations.AddField(
            model_name='salerevision',
            name='operation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='clave de operación'),
        ),
        migrations.CreateModel(
            name='CustomerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='clave de operación')),
                ('revision_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número de edición')),
                ('reason', models.TextField(verbose_name='motivo de la edición')),
                ('snapshot', models.JSONField(verbose_name='copia completa anterior')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='archivada el')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.customer', verbose_name='cliente actual')),
            ],
            options={
                'verbose_name': 'versión anterior de cliente',
                'verbose_name_plural': 'versiones anteriores de clientes',
                'ordering': ['-archived_at', '-pk'],
                'indexes': [models.Index(fields=['archived_at'], name='customer_revision_archived_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'revision_number'), name='customer_revision_unique_number')],
            },
        ),
    ]
