# Generated by Django 5.2.16 on 2026-09-17 07:16

import django.db.models.deletion
from django.db import migrations, models


def enable_daily_frequency(apps, schema_editor):
    business_settings = apps.get_model("core", "BusinessSettings")
    for settings in business_settings.objects.all():
        frequencies = list(settings.available_frequencies or [])
        if "daily" not in frequencies:
            settings.available_frequencies = ["daily", *frequencies]
            settings.save(update_fields=["available_frequencies"])


def disable_daily_frequency(apps, schema_editor):
    business_settings = apps.get_model("core", "BusinessSettings")
    for settings in business_settings.objects.all():
        settings.available_frequencies = [
            item for item in (settings.available_frequencies or []) if item != "daily"
        ]
        settings.save(update_fields=["available_frequencies"])


def backfill_habitual_collectors(apps, schema_editor):
    collection_assignment = apps.get_model("core", "CollectionAssignment")
    customer_collector_link = apps.get_model("core", "CustomerCollectorLink")
    latest_by_customer = []
    seen_customers = set()
    assignments = (
        collection_assignment.objects.select_related("route", "route__collector")
        .filter(
            customer__is_active=True,
            route__collector__is_active=True,
            route__collector__archived_at__isnull=True,
        )
        .order_by("customer_id", "-assigned_date", "-pk")
    )
    for assignment in assignments.iterator():
        if assignment.customer_id in seen_customers:
            continue
        seen_customers.add(assignment.customer_id)
        latest_by_customer.append(
            customer_collector_link(
                customer_id=assignment.customer_id,
                collector_id=assignment.route.collector_id,
                started_at=assignment.assigned_date,
                source_route_id=assignment.route_id,
                reason="Asignación habitual recuperada de la última planilla anterior",
            )
        )
    customer_collector_link.objects.bulk_create(latest_by_customer)


def remove_backfilled_habitual_collectors(apps, schema_editor):
    customer_collector_link = apps.get_model("core", "CustomerCollectorLink")
    customer_collector_link.objects.filter(
        reason="Asignación habitual recuperada de la última planilla anterior"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_collector_safe_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('biweekly', 'Cada 2 semanas'), ('monthly', 'Mensual')], max_length=16, verbose_name='frecuencia'),
        ),
        migrations.RunPython(enable_daily_frequency, disable_daily_frequency),
        migrations.CreateModel(
            name='CustomerCollectorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('started_at', models.DateField(verbose_name='asignado desde')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='asignación finalizada el')),
                ('reason', models.CharField(default='Asignación guardada desde Preparar planillas', max_length=250, verbose_name='motivo')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_links', to='core.collector', verbose_name='cobrador')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collector_links', to='core.customer', verbose_name='cliente')),
                ('source_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitual_links_created', to='core.collectionroute', verbose_name='recorrido de origen')),
            ],
            options={
                'verbose_name': 'cobrador habitual del cliente',
                'verbose_name_plural': 'historial de cobradores habituales',
                'ordering': ['-started_at', '-pk'],
                'indexes': [models.Index(fields=['collector', 'ended_at'], name='customer_collector_active_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('customer',), name='customer_collector_one_active'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='customer_collector_valid_period')],
            },
        ),
        migrations.CreateModel(
            name='LateFeePausePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('paused_from', models.DateField(verbose_name='pausado desde')),
                ('resumed_at', models.DateField(blank=True, null=True, verbose_name='reanudado el')),
                ('reason', models.TextField(verbose_name='motivo de la pausa')),
                ('resume_reason', models.TextField(blank=True, verbose_name='motivo de la reanudación')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='late_fee_pause_periods', to='core.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'pausa de recargo diario',
                'verbose_name_plural': 'pausas de recargo diario',
                'ordering': ['-paused_from', '-pk'],
                'indexes': [models.Index(fields=['sale', 'resumed_at'], name='late_fee_pause_sale_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('resumed_at__isnull', True)), fields=('sale',), name='late_fee_pause_one_open_sale'), models.CheckConstraint(condition=models.Q(('resumed_at__isnull', True), ('resumed_at__gte', models.F('paused_from')), _connector='OR'), name='late_fee_pause_valid_period')],
            },
        ),
        migrations.RunPython(
            backfill_habitual_collectors,
            remove_backfilled_habitual_collectors,
        ),
    ]
